name: Secret Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trufflehog:
    name: TruffleHog Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./

          extra_args: --debug --only-verified
